debug: false
device: "cuda"
seed: 42
classes:
  - Fire_Disaster
  - Human_Damage
  - Water_Disaster
  - Land_Disaster
  - Damaged_Infrastructure
  - Non_Damage
path: "/kaggle/input/disaster/Comprehensive Disaster Dataset(CDD)"
batch_size: 64
num_workers: os.cpu_count()
split: [0.65, 0.20, 0.15]
input_size: [224, 224]
num_epochs: 5
loss_fn: torch.nn.CrossEntropyLoss
